name: Deploy on yuvalinguist.space

on:
  workflow_dispatch:

jobs:
  build-core:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Validate Gradle wrapper
      uses: gradle/wrapper-validation-action@ccb4328a959376b642e027874838f60f8e596de3

    - name: Test core
      uses: gradle/gradle-build-action@v2
      with:
        arguments: jsTest
        build-root-directory: npbloom-core

    - name: Build core
      uses: gradle/gradle-build-action@v2
      with:
        arguments: build
        build-root-directory: npbloom-core

    - name: Upload core build
      uses: actions/upload-artifact@v4.6.0
      with:
        name: core-build-artifact
        path: npbloom-core/build/dist/js/productionLibrary
        retention-days: 7

  build-web:
    needs: build-core
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install
      run: npm install
      working-directory: npbloom-web

    - name: Download core build
      uses: actions/download-artifact@v4.1.8
      with:
        name: core-build-artifact
        path: npbloom-web/node_modules/npbloom-core

    - name: Build web
      run: npm run build
      working-directory: npbloom-web

    - name: Upload web build
      uses: actions/upload-artifact@v4.6.0
      with:
        name: web-build-artifact
        path: npbloom-web/dist
        retention-days: 7

  deploy:
    needs: build-web
    runs-on: ubuntu-latest

    steps:
    - name: Download web build
      uses: actions/download-artifact@v4.1.8
      with:
        name: web-build-artifact
        path: npbloom-web-dist

    - name: Deploy over FTP
      uses: sand4rt/ftp-deployer@v1.7
      with:
        sftp: true
        host: yuvalinguist.space
        port: 22
        username: ${{ secrets.YS_FTP_USERNAME }}
        password: ${{ secrets.YS_FTP_PASSWORD }}
        remote_folder: ${{ secrets.YS_REMOTE_FOLDER }}
        local_folder: npbloom-web-dist
        cleanup: true
