name: Deploy on yuvsstuff.net

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js 18.x
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build
      run: |
        npm install
        npm run build

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.2
      with:
        name: build-artifact
        path: build
        retention-days: 7

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v2.1.1
      with:
        name: build-artifact
        path: build

    - name: Deploy over FTP
      uses: sand4rt/ftp-deployer@v1.7
      with:
        sftp: true
        host: yuvsstuff.net
        port: 22
        username: ${{ secrets.YS_FTP_USERNAME }}
        password: ${{ secrets.YS_FTP_PASSWORD }}
        remote_folder: ${{ secrets.YS_REMOTE_FOLDER }}
        local_folder: build
        cleanup: true
